// Read-only integration demo: each answer reads the current CRM state.
export function initAssistant({snapshot, navigate, openDeal}) {
  const root=document.createElement('div');root.id='grain-assistant';
  root.innerHTML=`<button class="wheat-launcher" aria-label="Открыть помощника Колосок" aria-expanded="false" aria-controls="wheat-chat" title="Колосок · нажмите для чата, потяните для перемещения"><svg viewBox="0 0 100 120" aria-hidden="true"><g class="wheat-sway" stroke="#705227" stroke-width="2.5" stroke-linecap="round"><path d="M50 99V20" fill="none"/><g fill="#e6b94e"><ellipse cx="50" cy="16" rx="8" ry="13"/><ellipse cx="37" cy="29" rx="9" ry="16" transform="rotate(-35 37 29)"/><ellipse cx="63" cy="29" rx="9" ry="16" transform="rotate(35 63 29)"/><ellipse cx="33" cy="48" rx="10" ry="17" transform="rotate(-40 33 48)"/><ellipse cx="67" cy="48" rx="10" ry="17" transform="rotate(40 67 48)"/><ellipse cx="37" cy="67" rx="10" ry="16" transform="rotate(-40 37 67)"/><ellipse cx="63" cy="67" rx="10" ry="16" transform="rotate(40 63 67)"/></g><path d="M47 95Q23 91 23 79Q42 76 47 95M53 95Q76 91 77 79Q59 76 53 95" fill="#2e7651"/><path d="M47 99l-9 13M53 99l9 13M26 64l-12 8M74 64l12-10" fill="none"/><g fill="#253e30" stroke="none"><ellipse cx="43" cy="52" rx="3" ry="4"/><ellipse cx="57" cy="52" rx="3" ry="4"/></g><path d="M44 62q6 7 12 0" fill="none"/></g></svg><span>Спросить Колоска</span></button><section id="wheat-chat" class="wheat-chat" aria-label="Чат с Колоском" hidden><header><div><strong>Колосок</strong><small>Демонстрация помощника Grain CRM</small></div><button class="wheat-close" aria-label="Закрыть чат">×</button></header><div class="wheat-role"><label>Сценарий <select aria-label="Роль в демонстрации"><option value="executive">Руководитель</option><option value="manager">Менеджер</option></select></label><small>Демо · без внешнего ИИ</small></div><div class="wheat-messages" role="log" aria-live="polite" aria-relevant="additions"></div><div class="wheat-chips"></div><form><label class="wheat-input-label" for="wheat-input">Ваш вопрос</label><div class="wheat-compose"><input id="wheat-input" maxlength="1000" autocomplete="off" placeholder="Сколько зерна в Джурджулештах?" required><button type="submit" aria-label="Отправить вопрос">↑</button></div></form><footer>Ответы рассчитаны по данным CRM на дату демо. Сообщения не отправляются во внешние сервисы.</footer></section>`;
  document.body.append(root);
  const launcher=root.querySelector('.wheat-launcher'),panel=root.querySelector('.wheat-chat'),log=root.querySelector('.wheat-messages'),input=root.querySelector('input'),role=root.querySelector('select'),chips=root.querySelector('.wheat-chips');
  const n=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(v);
  function message(text,who='assistant',actions=[]){const el=document.createElement('article');el.className='wheat-message '+who;const p=document.createElement('p');p.textContent=text;el.append(p);for(const a of actions){const b=document.createElement('button');b.textContent=a.label;b.onclick=()=>{a.run();close()};el.append(b)}log.append(el);log.scrollTop=log.scrollHeight;}
  function close(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.focus()}
  function toggle(){panel.hidden=!panel.hidden;launcher.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)input.focus()}
  function suggestions(){chips.replaceChildren();for(const text of role.value==='executive'?['Остаток зерна в Джурджулештах','Заполненность терминала','Что сейчас в пути?']:['Помоги заполнить контракт','Статусы согласования']){const b=document.createElement('button');b.textContent=text;b.onclick=()=>ask(text);chips.append(b)}}
  function ask(text){message(text,'user');const s=snapshot(),q=text.toLowerCase().replace(/ё/g,'е');const executive=role.value==='executive';
    if(/терминал|джур|чулеш|giurg|jule|остат|заполнен|занятост|зерн/.test(q)){
      if(!executive){message('Переключите сценарий на «Руководитель», чтобы показать сводку терминала. Переключатель демонстрационный; в рабочей системе права задаются учётной записью.');return}
      if(/рени|констанц|одесс|друг(ой|ого)/.test(q)){message('В демонстрации есть данные только терминала Джурджулешты. По указанному терминалу данных нет.');return}
      const t=s.terminal;if(!t){message('Данные терминала недоступны.');return}
      message(`${t.name}\nНа дату демо ${s.date}:\nЗерновые — ${n(t.grain)} т.\nУдобрения — ${n(t.fertilizers)} т.${t.other?'\nПрочие товары — '+n(t.other)+' т.':''}\nВсего на хранении — ${n(t.total)} т.\nВместимость — ${n(t.capacity)} т.\nЗаполненность склада — ${t.capacity>0?n(t.total/t.capacity*100)+'%':'нет данных о вместимости'}.\nСвободная вместимость — ${n(Math.max(0,t.capacity-t.total))} т.\n\nЭто доля занятой вместимости по всем товарам, а не скорость перевалки. Источник: текущие складские партии и справочник терминалов.`, 'assistant',[{label:'Открыть дашборд руководителя',run:()=>navigate('executive')}]);return;
    }
    if(/пути|логист|задерж|отгруз|прогноз/.test(q)){message(`В пути (включая задержанные перевозки): ${n(s.inTransit)} т.\nЗадержанных перевозок: ${s.delayed}.\nИсточник: логистические перемещения демо на ${s.date}. Это текущие статусы, не прогноз ИИ.`, 'assistant',[{label:'Посмотреть отгрузки',run:()=>navigate('shipments')}]);return}
    if(/согласован|юрист|статус/.test(q)){const counts={};for(const d of s.documents)counts[d.stage]=(counts[d.stage]||0)+1;const names={draft:'Черновики',legal:'На проверке юриста',director:'У директора',signed:'Подписаны',rework:'На доработке',approved:'Согласованы'};message('Документы в CRM:\n'+Object.entries(counts).map(([k,v])=>`${names[k]||k}: ${v}`).join('\n')+'\n\nМаршрут: менеджер → юрист → коммерческий директор → подписание.', 'assistant',[{label:'Открыть документооборот',run:()=>navigate('documents')}]);return}
    if(/контракт|договор|заполн|agro|агро/.test(q)){
      const named=s.deals.find(d=>q.includes(d.client.toLowerCase())||q.includes(d.sourceId.toLowerCase()));
      if(!named&&!/agro|агро/.test(q)){message('Выберите сделку для подготовки данных договора. Я покажу поля из CRM и отмечу, что необходимо проверить.', 'assistant',s.deals.slice(0,3).map(d=>({label:d.sourceId+' · '+d.client,run:()=>openDeal(d.id)})));message('Для демонстрации напишите: «Помоги заполнить контракт Agro Nord».');return}
      const d=named||s.deals.find(d=>/agro nord/i.test(d.client));if(!d){message('Сделка не найдена. Укажите её номер из CRM.');return}
      message(`Данные для проверки договора ${d.sourceId}:\nКлиент: ${d.client}.\nТовар: ${d.product}.\nОбъём по партиям: ${n(d.parts.reduce((a,p)=>a+p.qty,0))} т.\nЦена из сделки: ${n(d.price)} MDL/т (${d.fixed?'зафиксирована':'предварительная'}).\nГрафик: ${d.parts.map(p=>p.date+' — '+n(p.qty)+' т').join('; ')||'не заполнен'}.\n\nПроверьте реквизиты, качество, базис поставки и условия оплаты. Данные показаны для подготовки; договор не изменён и не согласован.`, 'assistant',[{label:'Открыть карточку для заполнения',run:()=>openDeal(d.id)}]);return}
    message('В этой демонстрации я понимаю вопросы об остатках и заполненности Джурджулешт, товарах в пути, статусах согласования и данных для договора Agro Nord. Попробуйте одну из подсказок ниже.');
  }
  launcher.addEventListener('click',()=>{if(!dragged)toggle();dragged=false});root.querySelector('.wheat-close').onclick=close;root.querySelector('form').onsubmit=e=>{e.preventDefault();const t=input.value.trim();if(t){ask(t);input.value=''}};role.onchange=()=>{suggestions();message('Выбран сценарий: '+role.selectedOptions[0].textContent)};root.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close()});
  let start=null,dragged=false;launcher.onpointerdown=e=>{if(e.button!==0)return;const r=launcher.getBoundingClientRect();start={x:e.clientX,y:e.clientY,left:r.left,top:r.top};dragged=false;launcher.setPointerCapture(e.pointerId)};
  launcher.onpointermove=e=>{if(!start)return;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)dragged=true;if(dragged){root.style.left=Math.max(0,Math.min(innerWidth-130,start.left+e.clientX-start.x))+'px';root.style.top=Math.max(0,Math.min(innerHeight-140,start.top+e.clientY-start.y))+'px';root.style.bottom='auto'}};
  launcher.onpointerup=()=>{start=null};launcher.onpointercancel=()=>{start=null;dragged=false};window.addEventListener('resize',()=>{root.style.left='16px';root.style.top='auto';root.style.bottom='16px'});
  message('Я Колосок. Покажу, как помощник может отвечать по данным CRM. Например: «Сколько зерна на терминале Джурджулешты?» Числа рассчитываются при каждом запросе; внешний ИИ не подключён.');suggestions();
}
