import http from 'node:http';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium as pw} from 'playwright';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const projectRoot=fileURLToPath(new URL('..',import.meta.url));
const output=process.env.AUDIT_ARTIFACT_DIR||path.join(projectRoot,'.audit-artifacts');fs.mkdirSync(output,{recursive:true});
const report=[];const check=(name,value)=>{assert.ok(value,name);report.push(name)};
const expose=`window.testCRM={get deals(){return deals},get docs(){return wfDocs},financeState,cashMovements,terminalState,arAccounts,arCheck,arAmount,arFingerprint,pipelineVolume,financeCalc,financeContext,financeRow,financeGate,canFinanciallyLock,executiveFinance,executiveTerminalStats,analyticsUniverse,analyticsAllocationRows,analyticsAggregate,detail,clientDialog,wfOpen,wfTransition,wfSeverity,wfTick,setNow:v=>wfNow=v,get now(){return wfNow},arOpen,arDecide,openFinancial,openIntegrity,render:arRefresh,syncPlannedCashBase,hasSignedContract};`;
const server=http.createServer((req,res)=>{let path=projectRoot+(req.url==='/'?'/index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.json')?'application/json':'text/html');let content=fs.readFileSync(path);if(path.endsWith('index.html'))content=content.toString().replace('</script></body>',expose+'</script></body>');res.end(content)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8765,r));
const browser=await pw.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:8765');await page.waitForFunction(()=>window.testCRM);check('Startup without JS errors',!errors.length);
 const nav=await page.locator('nav [data-view]').evaluateAll(es=>es.map(e=>e.dataset.view));for(const view of nav){await page.locator('nav [data-view="'+view+'"]').click();check('Navigation '+view,await page.locator('#'+view).isVisible())}
 check('12 original questions + messenger supplement',await page.locator('#managerqa .manager-qa-card').count()===13);
 check('8 original sections + supplement',await page.locator('#managerqa .qa-group').count()===9);
 for(const s of await page.locator('#managerqa summary').all()){await s.click();check('Q&A accordion opens: '+(await s.innerText()).slice(0,45),await s.evaluate(e=>e.parentElement.open));await s.click()}
 await page.locator('nav [data-view="pipeline"]').click();check('Six funnel stages',await page.locator('.funnel-step').count()===6);await page.locator('.funnel-step').first().click();
 // Verify every entity drilldown, not only one sample.
 const ids=await page.evaluate(()=>testCRM.deals.map(x=>x.id));for(const id of ids){await page.evaluate(id=>testCRM.detail(id),id);check('Deal '+id,await page.locator('#detail').isVisible());await page.locator('#detail button.close').click()}
 for(let id=1;id<=10;id++){await page.evaluate(id=>testCRM.clientDialog(id),id);check('Client '+id,await page.locator('#client-detail').isVisible());await page.locator('#client-detail .close').click()}
 const docs=await page.evaluate(()=>testCRM.docs.map(x=>x.id));for(const id of docs){await page.evaluate(id=>testCRM.wfOpen(id),id);check('Document '+id,await page.locator('#document-detail').isVisible());await page.locator('#document-detail .close').click()}
 const shipments=await page.evaluate(()=>testCRM.deals.flatMap(x=>x.parts.map(p=>p.shipmentId)));for(const id of shipments){for(const [fn,modal] of [['arOpen','clearance-detail'],['openFinancial','financial-detail'],['openIntegrity','integrity-detail']]){await page.evaluate(({fn,id})=>testCRM[fn](id),{fn,id});check(fn+' '+id,await page.locator('#'+modal).isVisible());await page.locator('#'+modal+' .close').click()}}
 const result=await page.evaluate(()=>{const t=testCRM,s=t.executiveTerminalStats(),a=t.analyticsAggregate(t.analyticsUniverse(),t.analyticsAllocationRows());return {stock:s.current,capacity:s.capacity,fill:s.utilization,allFinite:Object.values(a).every(Number.isFinite),transit:t.deals.map(d=>({id:d.sourceId,pipeline:t.pipelineVolume(d)}))}});check('Terminal stock 420, capacity 1500, utilization 28',result.stock===420&&result.capacity===1500&&Math.abs(result.fill-28)<0.0001);check('Analytical aggregates finite',result.allFinite);

 // Negative financial and SLA rules, plus form actions.
 const rules=await page.evaluate(()=>{const t=testCRM,d=t.deals.find(d=>d.sourceId==='GR-003'),p=d.parts[0],row=t.financeRow(p.shipmentId),a=t.arAccounts[d.clientId];a.synced=t.now;a.overdue=10;const overdue=t.arCheck(p.shipmentId);const doc=t.docs.find(d=>d.stage==='legal');t.setNow(doc.due);const late=t.wfSeverity(doc);t.setNow(doc.due+3600000);t.wfTick();return {overdue:!overdue.allow&&overdue.reasons.some(x=>x.includes('Просроченный')),late,escalated:doc.escalated,lockBlocked:!t.canFinanciallyLock(row,{d,p}).ok}});
 check('Overdue debt blocks shipment',rules.overdue);check('SLA becomes late at deadline',rules.late==='late');check('Unresolved SLA escalates after an hour',rules.escalated);check('Incomplete/unshipped finance cannot lock',rules.lockBlocked);
 await page.locator('nav [data-view="clients"]').click();await page.locator('#client-search').fill('несуществующий клиент 999');check('Client search excludes missing clients',await page.locator('#client-table [data-client]').count()===0);await page.locator('#client-search').fill('Agro Nord');check('Client search finds Agro Nord',await page.locator('#client-table tbody tr').count()===1);await page.locator('#client-search').fill('');
 await page.evaluate(()=>testCRM.openFinancial('SH-001'));await page.locator('#cash-add').click();check('Cash requires date amount and category',!!await page.locator('#cash-error').innerText());await page.locator('#financial-detail .close').click();
 await page.evaluate(()=>testCRM.arOpen('SH-003'));await page.locator('#ar-urgent').click();await page.locator('#ar-send-request').click();check('Urgent exception requires reason',!!await page.locator('#ar-error').innerText());await page.locator('#ar-reason').fill('Согласованная срочная поставка — демонстрация');await page.locator('#ar-send-request').click();check('Urgent exception creates director task',(await page.locator('#clearance-detail').innerText()).includes('на рассмотрении'));await page.locator('#clearance-detail .close').click();
 await page.reload();await page.waitForFunction(()=>window.testCRM);
 // Signed workflow and negative control: no skipping the lawyer.
 const wf=await page.evaluate(()=>{const t=testCRM,d=t.docs.find(x=>x.stage==='legal'),deal=t.deals.find(x=>x.id===d.dealId);const skip=t.wfTransition({...d,stage:'director',approvals:[]},'approve');const a=t.wfTransition(d,'approve'),b=t.wfTransition(d,'approve'),c=t.wfTransition(d,'sign');return {skip,a,b,c,stage:d.stage,dealStage:deal.stage,signed:t.hasSignedContract(deal)}});check('Approval cannot skip lawyer',!!wf.skip);check('Lawyer → director → signed synchronizes deal',!wf.a&&!wf.b&&!wf.c&&wf.stage==='signed'&&wf.dealStage===4&&wf.signed);
 await page.reload();await page.waitForFunction(()=>window.testCRM);
 const edge=await page.evaluate(()=>{const t=testCRM,d=t.deals[0],p=d.parts[0],r=t.financeRow(p.shipmentId),old=t.arFingerprint(d,0);r.finalPrice=4000;const amount=t.arAmount(d,0),changed=t.arFingerprint(d,0)!==old;p.shipped=p.qty;const closed=t.pipelineVolume(d);p.shipped=0;p.date='2026-11-02';r.paymentTermsDays=10;t.syncPlannedCashBase(p.shipmentId,r,{d,p});const cash=t.cashMovements.find(m=>m.shipmentId===p.shipmentId&&m.direction==='in'&&m.source==='Коммерческие условия');const before=JSON.stringify(t.executiveFinance().months);t.cashMovements.push({id:'test-actual',date:'2026-10-01',status:'actual',direction:'in',amount:999999});return {amount,changed,closed,cashDate:cash.date,cashAmount:cash.amount,planUnaffected:before===JSON.stringify(t.executiveFinance().months),blocked:!t.arCheck(p.shipmentId).allow}});check('AR amount uses shipment final price',edge.amount===2000000);check('Price change invalidates clearance fingerprint',edge.changed);check('Fully shipped pipeline volume zero',edge.closed===0);check('Cash amount and payment date synchronized',edge.cashDate==='2026-11-12'&&edge.cashAmount===2000000);check('Executive planned cash does not double count actual',edge.planUnaffected);check('Unsigned shipment blocked',edge.blocked);
 await page.reload();await page.waitForFunction(()=>window.testCRM);
 await page.getByRole('button',{name:'Открыть помощника Колосок'}).click();await page.getByRole('button',{name:'Остаток зерна в Джурджулештах',exact:true}).click();let chat=await page.locator('.wheat-messages').innerText();check('Assistant category split and capacity',chat.includes('Зерновые — 350 т')&&chat.includes('Удобрения — 70 т')&&chat.includes('28%'));
 await page.evaluate(()=>testCRM.terminalState.inventory[0].quantityTons=300);await page.getByRole('button',{name:'Заполненность терминала',exact:true}).click();chat=await page.locator('.wheat-message').last().innerText();check('Assistant reads live state, no canned amounts',chat.includes('390 т')&&chat.includes('460 т'));
 await page.locator('#wheat-input').fill('<img src=x onerror=alert(1)>');await page.getByRole('button',{name:'Отправить вопрос'}).click();check('Chat escapes user input',await page.locator('.wheat-messages img').count()===0);
 await page.locator('#wheat-input').fill('Помоги заполнить контракт Agro Nord');await page.getByRole('button',{name:'Отправить вопрос'}).click();check('Contract assistant reads deal', (await page.locator('.wheat-message').last().innerText()).includes('GR-001'));
 await page.getByRole('button',{name:'Закрыть чат'}).click();const b=await page.locator('.wheat-launcher').boundingBox();await page.mouse.move(b.x+40,b.y+30);await page.mouse.down();await page.mouse.move(b.x+180,b.y-100,{steps:8});await page.mouse.up();const b2=await page.locator('.wheat-launcher').boundingBox();check('Mascot draggable',b2.x>b.x+50);check('Drag does not open chat',!await page.locator('#wheat-chat').isVisible());
 await page.locator('nav [data-view="executive"]').click();check('Terminal scale has explanation',(await page.locator('#exec-terminal').innerText()).includes('Свободно'));await page.screenshot({path:path.join(output,'executive.png')});
 await page.locator('nav [data-view="pipeline"]').click();await page.screenshot({path:path.join(output,'funnel.png')});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Открыть помощника Колосок'}).click();await page.getByRole('button',{name:'Остаток зерна в Джурджулештах',exact:true}).click();const r=await page.locator('#wheat-chat').boundingBox();check('Mobile chat fits viewport',r.x>=0&&r.x+r.width<=390&&r.y+r.height<=844);await page.screenshot({path:path.join(output,'mobile.png')});
 check('No JS errors during all scenarios',errors.length===0);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed:report.length,checks:report,errors},null,2));console.log(JSON.stringify({passed:report.length,errors}));
}finally{await browser.close();server.close()}
